[package]
name = "sad"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "sad.rs"
name = "sad"

[dependencies]
docopt = "1"
serde = { version = "1", features = ["derive"] } # for docopt
toml = "0.7"
serde_yaml = "0.9"
serde_json = "1"
